
CREATE DATABASE IF NOT EXISTS jee_quiz;
USE jee_quiz;

-- Table to store all quiz questions (The Source of Truth)
CREATE TABLE questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    subject VARCHAR(50) NOT NULL,
    question_text TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_answer CHAR(1) NOT NULL -- 'A', 'B', 'C', or 'D'
);

-- Table to store student results (The Answer Sheet)
-- The raw_answers field stores a JSON string of all user inputs and question details for review
CREATE TABLE results (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_name VARCHAR(100) NOT NULL,
    subject VARCHAR(50) NOT NULL,
    total_score INT NOT NULL,
    date_taken DATETIME DEFAULT CURRENT_TIMESTAMP,
    raw_answers JSON NOT NULL -- Stores detailed JSON of the attempt for checking
);

-- Sample JEE Level Questions (Physics, Chemistry, Maths)

-- Physics
INSERT INTO questions (subject, question_text, option_a, option_b, option_c, option_d, correct_answer) VALUES
('Physics', 'A parallel plate capacitor is charged to a potential difference $V$. If the plates are moved apart, with the charging battery **disconnected**, the capacitance $C$ and potential difference $V$ will change to:', 'C decreases, V increases', 'C increases, V decreases', 'C and V both increase', 'C and V both decrease', 'A'),
('Physics', 'If the magnetic flux linked with a coil changes by $8 \\times 10^{-2}$ Wb in $0.2$ s, the induced EMF is:', '$0.4$ V', '$0.04$ V', '$4$ V', '$40$ V', 'A'),
('Physics', 'The effective resistance between points A and B in the circuit shown (each resistor is $R$) is: $$ \\begin{tikzpicture} \\draw (0,0) node[circ](A){A} -- (2,0) to[R](2,2) -- (0,2) to[R](0,0); \\draw (2,2) -- (4,2) to[R](4,0) -- (2,0); \\draw (4,0) node[circ](B){B}; \\end{tikzpicture} $$ ', '$R$', '$R/2$', '$2R$', '$3R/2$', 'B'),
('Physics', 'The period of a simple pendulum in Simple Harmonic Motion (SHM) is $T$. If its length is quadrupled, its new period will be:', '$T/2$', '$T/4$', '$2T$', '$4T$', 'C'),
('Physics', 'Which phenomenon is responsible for the splitting of white light into its constituent colors when passing through a prism?', 'Interference', 'Diffraction', 'Polarization', 'Dispersion', 'D'),
('Physics', 'A car increases its speed from $10$ m/s to $30$ m/s in $5$ seconds. What is its acceleration?', '$2$ m/s$^2$', '$4$ m/s$^2$', '$6$ m/s$^2$', '$8$ m/s$^2$', 'B'),
('Physics', 'The work done by the gravitational force on a satellite orbiting the Earth in a circular path is:', 'Positive', 'Negative', 'Zero', 'Cannot be determined', 'C'),
('Physics', 'What is the SI unit of power?', 'Joule', 'Newton', 'Watt', 'Volt', 'C'),
('Physics', 'In a step-up transformer, the number of turns in the primary coil compared to the secondary coil is:', 'Greater', 'Smaller', 'Equal', 'Not related', 'B'),
('Physics', 'Which of the following is an example of a scalar quantity?', 'Velocity', 'Force', 'Acceleration', 'Energy', 'D'),
('Physics', 'If a wave has a frequency of $50$ Hz and a wavelength of $2$ m, what is its speed?', '$25$ m/s', '$50$ m/s', '$100$ m/s', '$200$ m/s', 'C'),
('Physics', 'According to Ohm''s Law, the potential difference ($V$) across a conductor is directly proportional to the:', 'Resistance ($R$)', 'Current ($I$)', 'Power ($P$)', 'Charge ($Q$)', 'B'),
('Physics', 'The momentum of a body of mass $m$ moving with velocity $v$ is given by the formula:', '$m/v$', '$v/m$', '$m^2v$', '$mv$', 'D'),
('Physics', 'When an electron transitions from a higher energy level to a lower energy level in an atom, it:', 'Absorbs a photon', 'Emits a photon', 'Increases its energy', 'Stays in the same state', 'B'),
('Physics', 'The minimum distance required to hear a distinct echo at $25$°C (speed of sound $\\approx 346$ m/s) is approximately:', '$17.3$ m', '$34.6$ m', '$50$ m', '$10$ m', 'A'),
('Physics', 'The force experienced by a charge $q$ moving with velocity $\\mathbf{v}$ in a magnetic field $\\mathbf{B}$ is given by:', '$q\\mathbf{E}$', '$q(\\mathbf{v} \\times \\mathbf{B})$', '$q\\mathbf{v}$', '$q\\mathbf{B}$', 'B'),
('Physics', 'In a series RLC circuit, at resonance, the impedance is equal to:', 'Capacitive Reactance ($X_C$)', 'Inductive Reactance ($X_L$)', 'Resistance ($R$)', 'Zero', 'C'),
('Physics', 'A rocket works on the principle of conservation of:', 'Energy', 'Angular Momentum', 'Linear Momentum', 'Mass', 'C'),
('Physics', 'What is the dimensional formula for force?', '$[MLT^{-1}]$', '$[MLT^{-2}]$', '$[ML^{-1}T^{-2}]$', '$[ML^2T^{-2}]$', 'B'),
('Physics', 'If two bulbs of $60$ W and $100$ W are connected in parallel to a power source, which one will glow brighter?', '$60$ W bulb', '$100$ W bulb', 'Both equally bright', 'Depends on the wire thickness', 'B'),
('Physics', 'The critical angle is the angle of incidence for which the angle of refraction is:', '$0$°', '$45$°', '$90$°', '$180$°', 'C'),
('Physics', 'The process by which heat is transmitted through a vacuum is:', 'Conduction', 'Convection', 'Radiation', 'Insulation', 'C'),
('Physics', 'The half-life of a radioactive substance is $10$ days. After $20$ days, what fraction of the original sample will remain undecayed?', '$1/2$', '$1/4$', '$1/8$', '$1/16$', 'B'),
('Physics', 'Which component of an AC generator converts the induced AC to DC?', 'Slip Rings', 'Armature', 'Commutator (Split-ring)', 'Magnetic Field', 'C'),
('Physics', 'What is the correct relationship between the speed of light ($c$), frequency ($f$), and wavelength ($\\lambda$) of an electromagnetic wave?', '$c = f\\lambda$', '$c = f/\\lambda$', '$c = \\lambda/f$', '$c = f+\\lambda$', 'A');
('Physics', 'A solid cylinder of mass $M$ and radius $R$ rolls without slipping down an inclined plane of angle $\\theta$. The acceleration of the center of mass is:', '$$g \\sin\\theta$$', '$$\\frac{1}{2} g \\sin\\theta$$', '$$\\frac{2}{3} g \\sin\\theta$$', '$$\\frac{3}{2} g \\sin\\theta$$', 'C'),
('Physics', 'A particle is executing SHM with amplitude $A$. At what distance from the mean position is the potential energy equal to the kinetic energy?', '$$A$$', '$$A/2$$', '$$A/\\sqrt{2}$$', '$$A \\sqrt{2}$$', 'C'),
('Physics', 'Two bodies of masses $m_1$ and $m_2$ have equal kinetic energy. If $p_1$ and $p_2$ are their respective momenta, the ratio $p_1/p_2$ is:', '$$\\frac{m_1}{m_2}$$', '$$\\frac{m_2}{m_1}$$', '$$\\sqrt{\\frac{m_1}{m_2}}$$', '$$\\sqrt{\\frac{m_2}{m_1}}$$', 'C'),
('Physics', 'A satellite is orbiting the Earth at a height $h$. If $R$ is the radius of the Earth, its orbital velocity is proportional to:', '$$h$$', '$$R+h$$', '$$\\frac{1}{\\sqrt{R+h}}$$', '$$\\sqrt{R+h}$$', 'C'),
('Physics', 'In an inelastic collision between two bodies, which of the following remains conserved?', 'Kinetic Energy', 'Total Energy', 'Mechanical Energy', 'Elastic Potential Energy', 'B'),
('Physics', 'The moment of inertia of a uniform circular disc of mass $M$ and radius $R$ about an axis passing through its center and perpendicular to its plane is:', '$$MR^2$$', '$$\\frac{1}{2} MR^2$$', '$$\\frac{2}{5} MR^2$$', '$$\\frac{1}{4} MR^2$$', 'B'),
('Physics', 'A block of mass $M$ is placed on a rough inclined plane with coefficient of static friction $\\mu$. The maximum angle of inclination for which the block does not slide is $\\theta$. What is $\\mu$?', '$$\\sin\\theta$$', '$$\\cos\\theta$$', '$$\\tan\\theta$$', '$$\\cot\\theta$$', 'C'),
('Physics', 'An ideal fluid flows through a pipe of varying cross-section. The law governing the relation between pressure and velocity is:', 'Pascal''s Law', 'Stokes'' Law', 'Bernoulli''s Principle', 'Poiseuille''s Law', 'C'),
('Physics', 'For a transverse wave traveling on a string, the phase difference between two points separated by a distance $\\lambda/4$ (where $\\lambda$ is the wavelength) is:', '$$0$$', '$$\\pi/4$$', '$$\\pi/2$$', '$$\\pi$$', 'C'),
('Physics', 'The escape velocity of a body from the surface of Earth does not depend on:', 'Mass of the body', 'Mass of the Earth', 'Radius of the Earth', 'Gravitational Constant $G$', 'A'),
('Physics', 'The unit of surface tension in SI system is:', '$$N/m^2$$', '$$J/m^2$$', '$$N \\cdot m$$', '$$N/m$$', 'D'),
('Physics', 'A body floats in a liquid with a part of it immersed. The buoyant force is equal to:', 'Weight of the body', 'Volume of the body', 'Weight of the liquid displaced', 'Mass of the liquid displaced', 'C'),
('Physics', 'The center of mass of a system of particles will remain at rest if:', 'Net force is zero', 'Net torque is zero', 'Net momentum is non-zero', 'Kinetic energy is zero', 'A'),
('Physics', 'A body of mass $m$ is thrown vertically upwards with velocity $v$. The work done by air resistance during its upward journey is:', 'Positive', 'Negative', 'Zero', 'Depends on $v$', 'B'),
('Physics', 'For a rigid body rotating about a fixed axis, the angular momentum $\\mathbf{L}$ and angular velocity $\\boldsymbol{\\omega}$ are related by:', '$$\\mathbf{L} = M \\mathbf{r} \\times \\mathbf{v}$$', '$$\\mathbf{L} = I \\boldsymbol{\\omega}$$', '$$\\mathbf{L} = \\mathbf{I} \\boldsymbol{\\alpha}$$', '$$\\mathbf{L} = \\mathbf{F} \\times \\mathbf{r}$$', 'B'),
('Physics', 'The restoring force in SHM is proportional to the displacement and always directed towards the:', 'Amplitude', 'Extreme Position', 'Velocity Vector', 'Mean Position', 'D'),
('Physics', 'The modulus of rigidity (shear modulus) is relevant for which state of matter?', 'Solids only', 'Liquids only', 'Gases only', 'Liquids and Gases', 'A'),
('Physics', 'The maximum height attained by a projectile fired at an angle $\\theta$ with the horizontal and initial velocity $u$ is:', '$$u \\sin\\theta / g$$', '$$u^2 \\sin^2\\theta / 2g$$', '$$u^2 \\sin(2\\theta) / g$$', '$$u^2 \\cos^2\\theta / 2g$$', 'B'),
('Physics', 'The speed of sound in an ideal gas is proportional to the square root of:', 'Density', 'Pressure', 'Absolute Temperature', 'Volume', 'C'),
('Physics', 'If Earth suddenly shrinks to half its radius without any change in its mass, the duration of a day will become:', '$$6 \\text{ hours}$$', '$$12 \\text{ hours}$$', '$$24 \\text{ hours}$$', '$$48 \\text{ hours}$$', 'A'),
-- ------------------------------------------------------------------------------------------------------
-- ELECTROMAGNETISM (EM) - 25 Questions
-- ------------------------------------------------------------------------------------------------------
('Physics', 'Gauss''s Law for electrostatics is given by $\\oint \\mathbf{E} \\cdot d\\mathbf{A} = Q_{enclosed}/\\epsilon_0$. This law is most useful for calculating $\\mathbf{E}$ when the charge distribution has:', 'Uniform density', 'A finite boundary', 'Spherical symmetry', 'Simple magnitude', 'C'),
('Physics', 'The total energy stored in a parallel plate capacitor (capacitance $C$, voltage $V$) is:', '$$CV$$', '$$\\frac{1}{2} CV$$', '$$\\frac{1}{2} C^2V$$', '$$\\frac{1}{2} CV^2$$', 'D'),
('Physics', 'Two long parallel wires carrying currents $I_1$ and $I_2$ in the same direction:', 'Repel each other', 'Attract each other', 'Exert no force on each other', 'Create a torque on each other', 'B'),
('Physics', 'Kirchhoff''s junction rule is based on the conservation of:', 'Energy', 'Momentum', 'Charge', 'Mass', 'C'),
('Physics', 'Lenz''s Law is a consequence of the conservation of:', 'Charge', 'Momentum', 'Mass', 'Energy', 'D'),
('Physics', 'The impedance ($Z$) of a series RLC circuit at resonance is:', '$$\\sqrt{R^2 + (X_L - X_C)^2}$$', '$$X_L - X_C$$', '$$R$$', '$$X_L + X_C$$', 'C'),
('Physics', 'The electric potential inside a hollow conducting sphere with charge $Q$ is:', 'Zero', 'Constant and equal to the potential on the surface', 'Varies linearly with distance from center', 'Varies inversely with distance from center', 'B'),
('Physics', 'The Biot-Savart Law gives the magnetic field due to a:', 'Point charge', 'Moving charge', 'Current element', 'Magnetic pole', 'C'),
('Physics', 'A wire of resistance $R$ is cut into $n$ equal parts, which are then connected in parallel. The equivalent resistance of the combination is:', '$$R/n$$', '$$nR$$', '$$R/n^2$$', '$$n^2R$$', 'C'),
('Physics', 'In an AC circuit, the instantaneous power consumed by an inductor is zero when the phase difference between voltage and current is:', '$$0$$', '$$\\pi/4$$', '$$\\pi/2$$', '$$\\pi$$', 'C'),
('Physics', 'The rms value of AC current is defined as:', 'The average value of the current', 'The peak value divided by $\\sqrt{2}$', 'The peak value multiplied by $\\sqrt{2}$', 'The maximum value of the current', 'B'),
('Physics', 'If an electron beam enters a region perpendicular to a uniform magnetic field $\\mathbf{B}$, its path will be a:', 'Straight line', 'Parabola', 'Circle', 'Helix', 'C'),
('Physics', 'The magnetic field lines always form:', 'Open curves', 'Closed loops', 'Straight lines', 'Helical paths', 'B'),
('Physics', 'Displacement Current ($\\mathbf{J}_D$) is introduced in Maxwell''s equations to ensure the consistency of:', 'Gauss''s Law', 'Faraday''s Law', 'Ampere''s Circuital Law', 'Lorentz Force Law', 'C'),
('Physics', 'The self-inductance of a long solenoid is proportional to the square of the:', 'Length of the solenoid', 'Area of cross-section', 'Number of turns per unit length', 'Total number of turns ($N$)', 'D'),
('Physics', 'A potential difference is established across a Hall probe. The sign of the Hall voltage indicates the:', 'Magnitude of the charge carriers', 'Mass of the charge carriers', 'Density of the charge carriers', 'Sign of the charge carriers', 'D'),
('Physics', 'The electric field ($\\mathbf{E}$) and magnetic field ($\\mathbf{B}$) in an electromagnetic wave traveling in vacuum are:', 'Perpendicular to each other and to the direction of propagation', 'Parallel to each other', 'In the same phase', '$$E/B = 1/c$$ (where $c$ is speed of light)', 'A'),
('Physics', 'Dielectric strength is the maximum electric field an insulating material can withstand before:', 'It melts', 'It becomes superconducting', 'It starts conducting electricity', 'It turns into plasma', 'C'),
('Physics', 'A galvanometer is converted into an ammeter by connecting a low resistance shunt:', 'In series with the galvanometer', 'In parallel with the galvanometer', 'Only to the positive terminal', 'Only to the negative terminal', 'B'),
('Physics', 'The energy density stored in an electric field ($\\mathbf{E}$) in vacuum is given by:', '$$\\frac{1}{2} \\epsilon_0 E$$', '$$\\frac{1}{2} \\epsilon_0 E^2$$', '$$\\frac{1}{2} B^2/\\mu_0$$', '$$\\frac{1}{2} \\mu_0 H^2$$', 'B'),
('Physics', 'The electric field at a point is zero. The electric potential at that point must be:', 'Zero', 'Maximum', 'Minimum', 'Constant (may or may not be zero)', 'D'),
('Physics', 'Which of the following is true for a pure inductor connected to an AC source?', 'Current leads voltage by $\\pi/2$', 'Voltage leads current by $\\pi/2$', 'Current and voltage are in phase', 'Voltage lags current by $\\pi/2$', 'B'),
('Physics', 'Magnetic permeability ($\\mu$) is highest for which type of material?', 'Diamagnetic', 'Paramagnetic', 'Ferromagnetic', 'Non-magnetic', 'C'),
('Physics', 'The magnetic dipole moment of a current loop is independent of the:', 'Area of the loop', 'Current in the loop', 'Shape of the loop', 'Magnetic field $\\mathbf{B}$ applied externally', 'D'),
('Physics', 'According to Poynting vector $\\mathbf{S}$, the direction of energy flow in an EM wave is:', 'Parallel to $\\mathbf{E}$', 'Parallel to $\\mathbf{B}$', 'Parallel to $\\mathbf{E} \\times \\mathbf{B}$', 'Opposite to the wave propagation', 'C'),
-- ------------------------------------------------------------------------------------------------------
-- THERMODYNAMICS & OPTICS (TH/OPT) - 15 Questions
-- ------------------------------------------------------------------------------------------------------
('Physics', 'The molar specific heat at constant volume ($C_V$) for a monatomic ideal gas is:', '$$R$$', '$$3R/2$$', '$$5R/2$$', '$$7R/2$$', 'B'),
('Physics', 'In a cyclic thermodynamic process, the net work done by the system is equal to the:', 'Change in Internal Energy', 'Net Heat Exchanged', 'Change in Volume', 'Change in Pressure', 'B'),
('Physics', 'The efficiency ($\\eta$) of a Carnot engine operating between temperatures $T_h$ (source) and $T_c$ (sink) is given by:', '$$1 - T_c / T_h$$', '$$T_c / T_h$$', '$$T_h / T_c$$', '$$1 - T_h / T_c$$', 'A'),
('Physics', 'When a lens is immersed in a liquid of refractive index greater than that of the lens material, its focal length will:', 'Increase', 'Decrease', 'Remain unchanged', 'Become zero', 'A'),
('Physics', 'Rayleigh''s criterion for the limit of resolution of an optical instrument is based on the phenomenon of:', 'Interference', 'Polarization', 'Diffraction', 'Refraction', 'C'),
('Physics', 'In Young''s Double Slit Experiment (YDSE), if the wavelength of light is doubled, the fringe width will:', 'Be halved', 'Be doubled', 'Remain unchanged', 'Be quadrupled', 'B'),
('Physics', 'Which of the following processes occurs most nearly adiabatically in a real-world scenario?', 'Melting of ice', 'Quick bursting of a tyre', 'Boiling of water', 'Heating water in a kettle', 'B'),
('Physics', 'The phase change when light reflects from an interface of a **denser medium** to a **rarer medium** is:', '$$0$$', '$$\\pi/4$$', '$$\\pi/2$$', '$$\\pi$$', 'A'),
('Physics', 'The equation of state for a real gas, known as the van der Waals equation, incorporates corrections for:', 'Internal Energy and Pressure', 'Volume and Pressure', 'Internal Energy and Temperature', 'Volume and Temperature', 'B'),
('Physics', 'The total intensity in an interference pattern is not simply the sum of individual intensities ($I_1 + I_2$) because of the additional **term** related to:', 'Diffraction', 'Polarization', 'Phase difference', 'Absorption', 'C'),
('Physics', 'Total Internal Reflection (TIR) cannot occur when light travels from:', 'Glass to air', 'Water to air', 'Air to water', 'Diamond to glass', 'C'),
('Physics', 'The angle of prism is $A$ and the angle of minimum deviation is $\\delta_m$. The refractive index ($\\mu$) of the prism material is:', '$$\\sin(\\frac{A}{2}) / \\sin(\\frac{\\delta_m}{2})$$', '$$\\sin(\\frac{A+\\delta_m}{2}) / \\sin(\\frac{A}{2})$$', '$$\\sin(\\frac{A+\\delta_m}{2}) / \\sin(\\frac{\\delta_m}{2})$$', '$$\\sin(\\frac{A}{2}) / \\sin(\\frac{A+\\delta_m}{2})$$', 'B'),
('Physics', 'The change in entropy ($\\Delta S$) for an irreversible process is always:', 'Zero', 'Negative', 'Positive', 'Zero or Negative', 'C'),
('Physics', 'If the thermal conductivity of two rods of same area and length are $K_1$ and $K_2$, the equivalent conductivity when connected in **series** is:', '$$K_1 + K_2$$', '$$\\frac{K_1 K_2}{K_1 + K_2}$$', '$$\\frac{2 K_1 K_2}{K_1 + K_2}$$', '$$\\frac{K_1 + K_2}{2}$$', 'C'),
('Physics', 'A person with hypermetropia (farsightedness) uses which type of lens for correction?', 'Concave lens', 'Convex lens', 'Cylindrical lens', 'Bifocal lens', 'B'),
-- ------------------------------------------------------------------------------------------------------
-- MODERN PHYSICS & SEMICONDUCTORS (MP) - 15 Questions
-- ------------------------------------------------------------------------------------------------------
('Physics', 'The de Broglie wavelength ($\\lambda$) of a particle of mass $m$ and kinetic energy $K$ is given by:', '$$\\lambda = h / m v$$', '$$\\lambda = h / \\sqrt{2mK}$$', '$$\\lambda = h K / m$$', '$$\\lambda = \\sqrt{2mK} / h$$', 'B'),
('Physics', 'In the photoelectric effect, the stopping potential depends on the:', 'Intensity of incident light', 'Frequency of incident light', 'Distance between cathode and anode', 'Material of the window', 'B'),
('Physics', 'The binding energy per nucleon is maximum for which element, indicating maximum stability?', 'Hydrogen', 'Uranium', 'Iron (Fe)', 'Lead', 'C'),
('Physics', 'The radius of the $n^{th}$ Bohr orbit in a hydrogen atom is proportional to:', '$$n$$', '$$1/n$$', '$$n^2$$', '$$1/n^2$$', 'C'),
('Physics', 'Which of the following is true for $\\beta$-decay?', 'Atomic number decreases by 1', 'Atomic number increases by 1', 'Mass number decreases by 4', 'Mass number increases by 1', 'B'),
('Physics', 'The reverse bias voltage of a p-n junction diode leads to:', 'Increase in minority carrier current', 'Decrease in depletion region width', 'Increase in depletion region width', 'Increase in majority carrier current', 'C'),
('Physics', 'The energy of a photon is given by:', '$$\\frac{hc}{\\lambda^2}$$', '$$\\frac{h}{\\lambda}$$', '$$\\frac{hc}{\\lambda}$$', '$$\\frac{h\\lambda}{c}$$', 'C'),
('Physics', 'The law that relates the frequency of X-rays to the atomic number of the emitting element is:', 'Rutherford''s Law', 'Bohr''s Postulate', 'Moseley''s Law', 'Planck''s Law', 'C'),
('Physics', 'In a Common Emitter (CE) configuration, the output quantity is:', 'Emitter current ($I_E$)', 'Base current ($I_B$)', 'Collector current ($I_C$)', 'Input voltage ($V_{BE}$)', 'C'),
('Physics', 'The process in which a heavy nucleus splits into two or more lighter nuclei is called:', 'Fusion', 'Fission', 'Decay', 'Chain reaction', 'B'),
('Physics', 'The half-life ($T_{1/2}$) and decay constant ($\\lambda$) of a radioactive substance are related by:', '$$T_{1/2} = \\lambda / \\ln(2)$$', '$$T_{1/2} = \\ln(2) / \\lambda$$', '$$T_{1/2} = 1 / \\lambda$$', '$$T_{1/2} = \\lambda$$', 'B'),
('Physics', 'If the input of a two-input NOR gate is $A$ and $B$, the output $Y$ is given by:', '$$Y = A + B$$', '$$Y = \\overline{A \\cdot B}$$', '$$Y = \\overline{A + B}$$', '$$Y = A \\cdot B$$', 'C'),
('Physics', 'In Bohr''s model, the angular momentum of an electron in an orbit is an integral multiple of:', '$$h$$', '$$h / 2\\pi$$', '$$\\pi / h$$', '$$h / \\pi$$', 'B'),
('Physics', 'Which phenomenon demonstrates the particle nature of light?', 'Interference', 'Diffraction', 'Polarization', 'Photoelectric Effect', 'D'),
('Physics', 'A transistor is generally used as an:', 'Resistor and Capacitor', 'Amplifier and Switch', 'Inductor and Diode', 'Oscillator and Filter', 'B');

-- Chemistry
INSERT INTO questions (subject, question_text, option_a, option_b, option_c, option_d, correct_answer) VALUES
-- ------------------------------------------------------------------------------------------------------
-- INORGANIC CHEMISTRY (IOC) - 33 Questions
-- ------------------------------------------------------------------------------------------------------
('Chemistry', 'The number of unpaired electrons in a $d^6$ ion in a **high spin** octahedral field is:', '5', '4', '2', '0', 'B'),
('Chemistry', 'Which of the following elements has the highest first ionization enthalpy?', 'C', 'N', 'O', 'F', 'B'),
('Chemistry', 'The oxidation state of $\\text{Cr}$ in $\\text{K}_2\\text{Cr}_2\\text{O}_7$ is:', '+3', '+6', '+7', '+5', 'B'),
('Chemistry', 'Which hybridization and shape best describes the central atom in $\\text{XeF}_4$?', '$sp^3d^2$, square planar', '$sp^3d$, trigonal bipyramidal', '$sp^3d^2$, octahedral', '$sp^3$, tetrahedral', 'A'),
('Chemistry', 'Which of the following compounds is an example of an interstitial compound?', 'FeS', 'TiO', 'TiC', 'NaCl', 'C'),
('Chemistry', 'The major product formed when $\\text{Al}$ is reacted with concentrated $\\text{NaOH}$ solution is:', '$$\\text{Al}(\\text{OH})_3$$', '$$\\text{Na}\\[\\text{Al}(\\text{OH})_4\\]$$', '$$\\text{Al}_2\\text{O}_3$$', '$$\\text{Na}_3\\text{AlF}_6$$', 'B'),
('Chemistry', 'The structure of $\\text{PCl}_5$ in the solid state is:', 'Tetrahedral', 'Square pyramidal', 'Trigonal bipyramidal', '$$\\left[\\text{PCl}_4\\right]^{+}\\left[\\text{PCl}_6\\right]^{-}$$', 'D'),
('Chemistry', 'Which of the following is a diamagnetic species?', '$$\\text{O}_2$$', '$$\\text{B}_2$$', '$$\\text{C}_2$$', '$$\\text{N}_2$$', 'D'),
('Chemistry', 'The maximum number of hydrogen bonds formed by a single water molecule is:', '1', '2', '3', '4', 'D'),
('Chemistry', 'The correct order of $\\pi$-acid character of ligands is:', '$$\\text{CO} < \\text{CN}^{-} < \\text{NO}^+$$', '$$\\text{NO}^+ < \\text{CN}^{-} < \\text{CO}$$', '$$\\text{CN}^{-} < \\text{CO} < \\text{NO}^+$$', '$$\\text{NO}^+ < \\text{CO} < \\text{CN}^{-}$$', 'C'),
('Chemistry', 'The shape of $\\text{I}_3^{-}$ ion according to VSEPR theory is:', 'Bent', 'Linear', 'Trigonal planar', 'T-shaped', 'B'),
('Chemistry', 'The $\\text{E}^{ \\circ }$ value for $\\text{Mn}^{3+} / \\text{Mn}^{2+}$ is much more positive than for $\\text{Fe}^{3+} / \\text{Fe}^{2+}$ because:', '$$\\text{Mn}^{2+}$$ is $d^5$ and highly stable', '$$\\text{Mn}^{3+}$$ is larger than $\\text{Fe}^{3+}$', '$$\\text{Mn}^{3+}$$ is $d^4$ and very unstable', '$$\\text{Mn}^{3+}$$ has high ionization energy', 'A'),
('Chemistry', 'In the structure of diborane ($\\text{B}_2\\text{H}_6$), the number of $2$-center $2$-electron bonds (terminal $\\text{B-H}$) and $3$-center $2$-electron bonds (bridge $\\text{B-H}$ bonds) are:', '4 and 2', '2 and 4', '6 and 0', '4 and 4', 'A'),
('Chemistry', 'Which of the following oxides is **amphoteric**?', '$$\\text{Na}_2\\text{O}$$', '$$\\text{MgO}$$', '$$\\text{Al}_2\\text{O}_3$$', '$$\\text{SO}_2$$', 'C'),
('Chemistry', 'The number of unpaired electrons in $\\text{Ti}^{3+}$ (atomic number $\\text{Ti}=22$) is:', '0', '1', '2', '3', 'B'),
('Chemistry', 'Which of the following halides is the most covalent?', '$$\\text{NaCl}$$', '$$\\text{MgCl}_2$$', '$$\\text{AlCl}_3$$', '$$\\text{SiCl}_4$$', 'D'),
('Chemistry', 'The process of removal of an electron from an atom is called:', 'Electron affinity', 'Electronegativity', 'Ionization enthalpy', 'Hydration energy', 'C'),
('Chemistry', 'The geometry of a complex $\\left[\\text{Ni}(\\text{CN})_4\\right]^{2-}$ is:', 'Tetrahedral', 'Octahedral', 'Square planar', 'Trigonal bipyramidal', 'C'),
('Chemistry', 'Which alkali metal reacts most vigorously with water?', 'Li', 'Na', 'K', 'Cs', 'D'),
('Chemistry', 'The stability of the $+1$ oxidation state increases down the group in which block of elements?', '$s$-block', '$p$-block', '$d$-block', '$f$-block', 'B'),
('Chemistry', 'Which compound is known as an 'inorganic benzene'?', '$$\\text{B}_3\\text{N}_3\\text{H}_6$$', '$$\\text{C}_6\\text{H}_6$$', '$$\\text{B}_2\\text{H}_6$$', '$$\\text{NH}_3$$', 'A'),
('Chemistry', 'The most common oxidation state of the Lanthanides is:', '+2', '+3', '+4', '+5', 'B'),
('Chemistry', 'The phenomenon of inert pair effect is most pronounced in:', 'Group 13', 'Group 14', 'Group 15', 'Group 16', 'B'),
('Chemistry', 'The common structural unit in silicates is:', '$$\\text{SiO}_2$$', '$$\\text{SiO}_4^{4-}$$', '$$\\text{Si}_2\\text{O}_7^{6-}$$', '$$\\text{SiO}_3^{2-}$$', 'B'),
('Chemistry', 'In $\\text{Ni}(\\text{CO})_4$, the oxidation state of Nickel is:', '+4', '+2', '+1', '0', 'D'),
('Chemistry', 'Which of the following transition metals shows the highest number of oxidation states?', 'Fe', 'Cu', 'Mn', 'Cr', 'C'),
('Chemistry', 'The maximum bond order among the following diatomic species is:', '$$\\text{O}_2^{-}$$', '$$\\text{N}_2$$', '$$\\N}_2^{+}$$', '$$\\text{O}_2$$', 'B'),
('Chemistry', 'Which compound has both ionic and covalent bonds?', '$$\\text{CH}_4$$', '$$\\text{H}_2\\text{O}$$', '$$\\text{KCN}$$', '$$\\text{CCl}_4$$', 'C'),
('Chemistry', 'The number of $P-O-P$ bonds in cyclic metaphosphoric acid $\\left(\\text{HPO}_3\\right)_3$ is:', '0', '1', '2', '3', 'D'),
('Chemistry', 'Which of the following noble gases does not form clathrates?', 'Xe', 'Ar', 'He', 'Kr', 'C'),
('Chemistry', 'The standard reduction potential ($E^{\\circ}$) is a measure of:', 'Oxidizing power', 'Reducing power', 'Stability of the oxidized state', 'Reactivity with water', 'A'),
('Chemistry', 'The most acidic oxide among the following is:', '$$\\text{P}_4\\text{O}_6$$', '$$\\text{As}_2\\text{O}_3$$', '$$\\text{Sb}_2\\text{O}_3$$', '$$\\text{Bi}_2\\text{O}_3$$', 'A'),
('Chemistry', 'Which complex is used in cancer chemotherapy (Cisplatin)?', '$$\\left[\\text{Pt}(\\text{NH}_3)_4\\right]\\text{Cl}_2$$', '$$\\left[\\text{Pt}(\\text{NH}_3)_2\\text{Cl}_2\\right]$$', '$$\\text{K}_2\\left[\\text{PtCl}_4\\right]$$', '$$\\left[\\text{Ni}(\\text{CO})_4\\right]$$', 'B'),
-- ------------------------------------------------------------------------------------------------------
-- PHYSICAL CHEMISTRY (PC) - 34 Questions
-- ------------------------------------------------------------------------------------------------------
('Chemistry', 'The solubility product ($K_{sp}$) of $\\text{AgCl}$ is $1.6 \\times 10^{-10}$. What is the molar solubility of $\\text{AgCl}$ in $0.01$ M $\\text{NaCl}$ solution?', '$1.6 \\times 10^{-12}$ M', '$1.6 \\times 10^{-8}$ M', '$1.6 \\times 10^{-10}$ M', '$1.6 \\times 10^{-5}$ M', 'B'),
('Chemistry', 'For an endothermic reaction with a positive entropy change ($\\Delta S > 0$), the reaction will be spontaneous:', 'At all temperatures', 'At low temperatures', 'At high temperatures', 'Never spontaneous', 'C'),
('Chemistry', 'For a first-order reaction, the time required for $99.9\\%$ completion is approximately how many times the half-life ($t_{1/2}$)?', '5', '7', '10', '15', 'C'),
('Chemistry', 'Which property of a solution is independent of the nature of the solute?', 'Vapour pressure lowering', 'Elevation in boiling point', 'Osmotic pressure', 'All of the above (Colligative Properties)', 'D'),
('Chemistry', 'The coordination number of $\\text{Na}^{+}$ in $\\text{NaCl}$ crystal structure is:', '4', '6', '8', '12', 'B'),
('Chemistry', 'The standard electrode potential for the $\\text{Zn}^{2+}/\\text{Zn}$ electrode is $-0.76$ V. The standard Gibbs free energy change ($\\Delta G^{\\circ}$) for the reaction $\\text{Zn}^{2+} + 2e^{-} \\rightarrow \\text{Zn}$ is:', 'Negative', 'Positive', 'Zero', 'Cannot be determined', 'A'),
('Chemistry', 'The relationship between the equilibrium constant ($K_p$) and $K_c$ is $K_p = K_c (RT)^{\\Delta n}$. For the reaction $\\text{PCl}_5(g) \\rightleftharpoons \\text{PCl}_3(g) + \\text{Cl}_2(g)$, $\\Delta n$ is:', '-1', '0', '1', '2', 'C'),
('Chemistry', 'If the concentration of a reactant is doubled, and the reaction rate quadruples, the order of the reaction with respect to that reactant is:', '0', '1', '2', '3', 'C'),
('Chemistry', 'The depression in freezing point of a $0.1$ M solution of $\\text{Na}_2\\text{SO}_4$ will be approximately three times that of a $0.1$ M solution of:', 'Glucose', 'NaCl', 'CaCl$_2$', 'KNO$_3$', 'A'),
('Chemistry', 'Which law relates the vapour pressure of a solution to the mole fraction of the solvent?', 'Henry''s Law', 'Raoult''s Law', 'Dalton''s Law', 'Avogadro''s Law', 'B'),
('Chemistry', 'The energy of activation of a reaction is $100$ kJ/mol. The ratio of rate constants at $400$ K and $300$ K is given by $\\ln \\left(\\frac{k_{400}}{k_{300}}\\right) \\approx$:', '$10$', '$5$', '$3.5$', '$8.3$', 'D'),
('Chemistry', 'For a pure substance, the chemical potential ($\\mu$) is equal to the:', 'Molar volume', 'Molar enthalpy', 'Molar Gibbs free energy', 'Molar internal energy', 'C'),
('Chemistry', 'Which of the following is not a characteristic of a physisorption (physical adsorption) process?', 'It is non-specific', 'It is reversible', 'It is multilayered', 'It involves high enthalpy of adsorption', 'D'),
('Chemistry', 'The critical temperature ($T_c$) of a gas is related to the van der Waals constants ($a$ and $b$) by the formula:', '$$T_c = 8a/27Rb$$', '$$T_c = a/27Rb$$', '$$T_c = a/R$$', '$$T_c = 27Rb/8a$$', 'A'),
('Chemistry', 'The quantity that remains unchanged when a concentrated solution is diluted is:', 'Molarity', 'Molality', 'Number of moles of solute', 'Normality', 'C'),
('Chemistry', 'What is the change in oxidation state of $\\text{Mn}$ in the reaction $\\text{MnO}_4^{-} \\rightarrow \\text{Mn}^{2+}$ in acidic medium?', 'From $+7$ to $+2$', 'From $+6$ to $+2$', 'From $+7$ to $+4$', 'From $+5$ to $+2$', 'A'),
('Chemistry', 'The time taken for the concentration of a reactant in a second-order reaction to reduce from $1$ M to $0.5$ M is **half** the time taken to reduce from $0.5$ M to $0.25$ M. This statement is:', 'True', 'False', 'Only true for zero order', 'Only true for first order', 'B'),
('Chemistry', 'Which type of solid is characterized by very high melting points and hardness, such as diamond or silicon carbide?', 'Molecular solid', 'Ionic solid', 'Metallic solid', 'Covalent (Network) solid', 'D'),
('Chemistry', 'The unit of the rate constant for a zero-order reaction is:', '$$\\text{s}^{-1}$$', '$$\\text{mol}\\cdot\\text{L}^{-1}\\cdot\\text{s}^{-1}$$', '$$\\text{L}\\cdot\\text{mol}^{-1}\\cdot\\text{s}^{-1}$$', '$$\\text{L}^2\\cdot\\text{mol}^{-2}\\cdot\\text{s}^{-1}$$', 'B'),
('Chemistry', 'The limiting molar conductivity of a weak electrolyte cannot be determined graphically but can be calculated using:', 'Arrhenius Equation', 'Kohlrausch''s Law', 'Faraday''s Laws', 'Nernst Equation', 'B'),
('Chemistry', 'According to $\\Delta G = -nFE_{\\text{cell}}$, for a spontaneous cell reaction, the cell potential ($E_{\\text{cell}}$) must be:', 'Negative', 'Positive', 'Zero', 'Independent of $\\Delta G$', 'B'),
('Chemistry', 'The ratio of the most probable velocity, average velocity, and root mean square velocity of gas molecules is:', '$$1: \\sqrt{2}: \\sqrt{3}$$', '$$\\sqrt{2}: 1: \\sqrt{3}$$', '$$\\sqrt{2}: \\sqrt{8/\\pi}: \\sqrt{3}$$', '$$\\sqrt{3}: \\sqrt{8/\\pi}: \\sqrt{2}$$', 'C'),
('Chemistry', 'Which of the following is not a property of an ideal solution?', 'Follows Raoult''s law', '$\\Delta H_{\\text{mix}} = 0$', '$\\Delta S_{\\text{mix}} = 0$', '$\\Delta V_{\\text{mix}} = 0$', 'C'),
('Chemistry', 'The effect of catalyst in a chemical reaction is to:', 'Increase the $\\Delta H$', 'Decrease the $\\Delta G$', 'Increase the activation energy', 'Provide an alternative path with lower activation energy', 'D'),
('Chemistry', 'A non-ideal solution that shows positive deviation from Raoult''s law exhibits:', 'Boiling point minimum (Azeotrope)', 'Boiling point maximum (Azeotrope)', 'No azeotrope formation', 'Ideal behavior', 'A'),
('Chemistry', 'In a face-centered cubic ($\\text{FCC}$) structure, the number of atoms per unit cell is:', '1', '2', '4', '6', 'C'),
('Chemistry', 'What is the $\\text{pH}$ of a $10^{-8}$ M $\\text{HCl}$ solution?', '8', '7', 'Slightly less than 7', 'Slightly more than 7', 'C'),
('Chemistry', 'For an isothermal expansion of an ideal gas, $\\Delta U$ is:', 'Positive', 'Negative', 'Zero', 'Equal to work done ($w$)', 'C'),
('Chemistry', 'The half-life of a radioactive element is $10$ minutes. The time required for the amount of substance to reduce by $87.5\\%$ is:', '10 minutes', '20 minutes', '30 minutes', '40 minutes', 'C'),
('Chemistry', 'The entropy change for the freezing of water at $0^{\\circ}\\text{C}$ is:', 'Zero', 'Positive', 'Negative', 'Depends on pressure', 'C'),
('Chemistry', 'What is the cell notation for the standard $\\text{Daniell}$ cell?', '$$\\text{Zn} | \\text{Zn}^{2+} || \\text{Cu}^{2+} | \\text{Cu}$$', '$$\\text{Cu} | \\text{Cu}^{2+} || \\text{Zn}^{2+} | \\text{Zn}$$', '$$\\text{Zn} | \\text{Cu}^{2+} || \\text{Zn}^{2+} | \\text{Cu}$$', '$$\\text{Zn}^{2+} | \\text{Zn} || \\text{Cu} | \\text{Cu}^{2+}$$', 'A'),
('Chemistry', 'At the critical micelle concentration (CMC), the surface tension of the solution:', 'Increases sharply', 'Decreases sharply', 'Remains constant', 'First increases then decreases', 'B'),
('Chemistry', 'Which of the following is the standard unit of viscosity in SI units?', 'Poise', '$$\\text{N}\\cdot\\text{m}^{-2}$$', '$$\\text{kg}\\cdot\\text{m}^{-1}\\cdot\\text{s}^{-1}$$', '$$\\text{dyne}\\cdot\\text{cm}^{-2}$$', 'C'),
('Chemistry', 'For a spontaneous reaction, the $\\text{E}^{ \\circ }$ value of the overall cell reaction must be:', 'Negative', 'Positive', 'Zero', 'Cannot be determined', 'B'),
-- ------------------------------------------------------------------------------------------------------
-- ORGANIC CHEMISTRY (OC) - 33 Questions
-- ------------------------------------------------------------------------------------------------------
('Chemistry', 'Which of the following compounds has the highest $\\text{p}K_a$ value?', 'Acetic Acid', 'Phenol', 'Ethanol', 'Benzoic Acid', 'C'),
('Chemistry', 'The major product of the reaction between propanone and ethyl magnesium bromide followed by hydrolysis is:', '$$\\text{Butan-1-ol}$$', '$$\\text{2-Methylbutan-2-ol}$$', '$$\\text{Pentan-3-ol}$$', '$$\\text{Butan-2-ol}$$', 'B'),
('Chemistry', 'Which intermediate is formed during the reaction of $\\text{KCN}$ with a primary alkyl halide in a nucleophilic substitution reaction?', 'Carbocation', 'Carbanion', 'Free radical', 'Transition state', 'D'),
('Chemistry', 'The compound that undergoes $\\text{Cannizzaro}$ reaction is:', '$$\\text{Propanal}$$', '$$\\text{Ethanal}$$', '$$\\text{Benzaldehyde}$$', '$$\\text{Acetone}$$', 'C'),
('Chemistry', 'Which of the following has the highest basic strength in an aqueous medium?', '$$\\text{NH}_3$$', '$$\\text{CH}_3\\text{NH}_2$$', '$$\\left(\\text{CH}_3\\right)_2\\text{NH}$$', '$$\\left(\\text{CH}_3\\right)_3\\text{N}$$', 'C'),
('Chemistry', 'The compound that gives a positive $\\text{Tollens}$ test is:', '$$\\text{Acetone}$$', '$$\\text{Benzophenone}$$', '$$\\text{Formaldehyde}$$', '$$\\text{Ethanol}$$', 'C'),
('Chemistry', 'The hybridization of the carbon atom in the carbonyl group ($C=O$) is:', '$sp^3$', '$sp^2$', '$sp$', 'Not hybridized', 'B'),
('Chemistry', 'The reagent used to convert alkyl cyanides into primary amines is:', '$$\\text{LiAlH}_4$$', '$$\\text{PCl}_5$$', '$$\\text{H}_2\\text{SO}_4$$', '$$\\text{NaOH}$$', 'A'),
('Chemistry', 'Which of the following is a $\\text{Zwitter}$ ion?', '$$\\text{Glucose}$$', '$$\\text{Glycerol}$$', '$$\\text{Glycine}$$', '$$\\text{Sucrose}$$', 'C'),
('Chemistry', 'In the $\\text{Friedel-Crafts}$ alkylation of benzene, the electrophile generated is a:', 'Carbanion', 'Carbocation', 'Free radical', 'Nucleophile', 'B'),
('Chemistry', 'The type of isomerism shown by $n$-butane and isobutane is:', 'Chain isomerism', 'Positional isomerism', 'Functional isomerism', 'Metamerism', 'A'),
('Chemistry', 'The reaction of $\\text{CH}_3\\text{COOH}$ with $\\text{PCl}_5$ yields:', '$$\\text{CH}_3\\text{Cl}$$', '$$\\text{CH}_3\\text{COCl}$$', '$$\\text{CH}_3\\text{CH}_2\\text{Cl}$$', '$$\\text{CH}_3\\text{POCl}_2$$', 'B'),
('Chemistry', 'The reagent used to distinguish between $\\text{acetaldehyde}$ and $\\text{acetone}$ is:', '$$\\text{Tollens'' Reagent}$$', '$$\\text{Fehling''s Solution}$$', '$$\\text{Schiff''s Reagent}$$', 'All of the above', 'D'),
('Chemistry', 'The maximum number of stereoisomers for a compound with $n$ chiral centers is:', '$n$', '$2n$', '$2^n$', '$n^2$', 'C'),
('Chemistry', 'Which of the following compounds will exhibit **geometrical isomerism**?', '$$\\text{But-1-ene}$$', '$$\\text{2-Methylpropene}$$', '$$\\text{But-2-ene}$$', '$$\\text{Propene}$$', 'C'),
('Chemistry', 'The IUPAC name of $\\left(\\text{CH}_3\\right)_3\\text{C-OH}$ is:', '$$\\text{Butan-1-ol}$$', '$$\\text{2-Methylpropan-2-ol}$$', '$$\\text{Isobutanol}$$', '$$\\text{t-Butanol}$$', 'B'),
('Chemistry', 'The most stable carbocation among the following is:', '$$\\text{Methyl Carbocation}$$', '$$\\text{Primary Carbocation}$$', '$$\\text{Secondary Carbocation}$$', '$$\\text{Tertiary Carbocation}$$', 'D'),
('Chemistry', 'Which compound gives a bright red precipitate with the **Victor Meyer test**?', '$$\\text{Primary alcohol}$$', '$$\\text{Secondary alcohol}$$', '$$\\text{Tertiary alcohol}$$', '$$\\text{Phenol}$$', 'A'),
('Chemistry', 'The product of the $\\text{Kolbe}$ electrolysis of sodium acetate solution is:', 'Ethane', 'Methane', 'Ethene', 'Propane', 'A'),
('Chemistry', 'The reagent $\\text{SeO}_2$ (Selenium Dioxide) is used for the oxidation of which group?', 'Aldehydes to acids', 'Primary alcohols to aldehydes', 'Methylene group adjacent to a carbonyl group', 'Ketones to esters', 'C'),
('Chemistry', 'The type of polymer formed by the condensation of hexamethylenediamine and adipic acid is:', 'Nylon 6', 'Nylon 6,6', 'Teflon', 'Polythene', 'B'),
('Chemistry', 'The reaction of $\\text{primary amine}$ with $\\text{CHCl}_3$ and $\\text{KOH}$ is known as:', 'Hofmann bromamide degradation', 'Carbylamine reaction', 'Gattermann reaction', 'Reimer-Tiemann reaction', 'B'),
('Chemistry', 'Which of the following reagents is used to convert an $\\text{acid chloride}$ to an $\\text{aldehyde}$ (Rosenmund reduction)?', '$$\\text{LiAlH}_4$$', '$$\\text{H}_2/\\text{Pd}-\\text{BaSO}_4$$', '$$\\text{Zn}(\\text{Hg})/\\text{HCl}$$', '$$\\text{NaBH}_4$$', 'B'),
('Chemistry', 'The most stable free radical among the following is:', '$$\\text{Methyl radical}$$', '$$\\text{Primary radical}$$', '$$\\text{Secondary radical}$$', '$$\\text{Tertiary radical}$$', 'D'),
('Chemistry', 'The common linkage found in proteins is:', 'Glycosidic linkage', 'Ether linkage', 'Peptide linkage', 'Hydrogen bond', 'C'),
('Chemistry', 'The order of dipole moment for $\\text{Chlorobenzene}$, $\\text{p-Dichlorobenzene}$, and $\\text{o-Dichlorobenzene}$ is:', '$$p < m < o$$', '$$p < o < m$$', '$$o < m < p$$', '$$m < p < o$$', 'A'),
('Chemistry', 'The maximum number of hydrogen bonds formed by a molecule of $\\text{DNA}$ (two base pairs) is:', '4', '5', '6', '7', 'B'),
('Chemistry', 'The presence of an electron-withdrawing group ($\text{EWG}$) on benzoic acid:', 'Decreases acidity', 'Increases acidity', 'Has no effect on acidity', 'Converts it to a base', 'B'),
('Chemistry', 'The most common mechanism for the addition of $\\text{HBr}$ to propene in the presence of peroxide is:', 'Electrophilic Addition', 'Nucleophilic Addition', 'Free Radical Addition', 'Concerted Mechanism', 'C'),
('Chemistry', 'Which aromatic compound is more reactive than benzene towards $\\text{electrophilic substitution}$?', 'Nitrobenzene', 'Chlorobenzene', 'Toluene', 'Benzoic acid', 'C'),
('Chemistry', 'The final product of the reaction $\\text{Ethylene} \\xrightarrow[\\text{Cold dilute } \\text{KMnO}_4]{\\text{Baeyer''s Reagent}}$ is:', 'Ethanol', 'Ethanal', 'Ethane-1,2-diol (Glycol)', 'Ethene oxide', 'C'),
('Chemistry', 'The $\\text{Gabriel Phthalimide Synthesis}$ is used for the preparation of:', 'Primary aromatic amines', 'Secondary aliphatic amines', 'Primary aliphatic amines', 'Tertiary amines', 'C'),
('Chemistry', 'Which of the following vitamins contains the element $\\text{Co}$ (Cobalt)?', 'Vitamin C', 'Vitamin $\\text{B}_1$', 'Vitamin $\\text{B}_{12}$', 'Vitamin D', 'C');

-- Maths
INSERT INTO questions (subject, question_text, option_a, option_b, option_c, option_d, correct_answer) VALUES
-- ------------------------------------------------------------------------------------------------------
-- ALGEBRA (Matrices, Determinants, Complex Numbers, Sequence & Series, Permutations & Combinations, Probability) - 30 Questions
-- ------------------------------------------------------------------------------------------------------
('Maths', 'If $A$ is a square matrix of order $3$ such that $\\det(\\text{adj}(A)) = 4$, then $|A|$ is equal to:', '$4$ or $-4$', '$4$', '$2$', '$-2$', 'A'),
('Maths', 'The number of terms in the expansion of $(x+y+z)^n$ is:', '$n+1$', '$n+2$', '$$\\frac{(n+1)(n+2)}{2}$$', '$$n(n+1)$$', 'C'),
('Maths', 'The value of the determinant $\\begin{vmatrix} 1 & a & a^2 \\\\ 1 & b & b^2 \\\\ 1 & c & c^2 \\end{vmatrix}$ is:', '$$a+b+c$$', '$$0$$', '$$(a-b)(b-c)(c-a)$$', '$$(a+b)(b+c)(c+a)$$', 'C'),
('Maths', 'If $z = x + iy$ is a complex number such that $|z-2i| = 2$, then the locus of $z$ is:', 'A line', 'A parabola', 'A circle', 'An ellipse', 'C'),
('Maths', 'The sum of the series $1^2 + 2^2 + 3^2 + \\dots + n^2$ is:', '$$\\frac{n(n+1)}{2}$$', '$$\\frac{n(n+1)(2n+1)}{6}$$', '$$\\left[\\frac{n(n+1)}{2}\\right]^2$$', '$$(2n+1)^2$$', 'B'),
('Maths', 'The number of ways to arrange the letters of the word $\\text{ASSASSINATION}$ is:', '$$\\frac{13!}{3! \\cdot 4! \\cdot 2!}$$', '$$\\frac{13!}{3! \\cdot 4! \\cdot 2! \\cdot 2!}$$', '$$\\frac{13!}{3! \\cdot 2! \\cdot 2!}$$', '$$13!$$', 'B'),
('Maths', 'The probability of getting exactly 5 heads in 6 coin tosses is:', '$$\\frac{5}{64}$$', '$$\\frac{6}{64}$$', '$$\\frac{1}{64}$$', '$$\\frac{5}{32}$$', 'B'),
('Maths', 'If the roots of the equation $x^2 + kx + 12 = 0$ are in the ratio $1:3$, then the value of $k$ is:', '$8$', '$4$', '$-8$', '$\\pm 8$', 'D'),
('Maths', 'The argument of the complex number $z = 1 - i \\sqrt{3}$ is:', '$$\\pi/6$$', '$$-2\\pi/3$$', '$$-5\\pi/6$$', '$$-60^{\\circ}$$', 'D'),
('Maths', 'The characteristic equation of a matrix $A = \\begin{pmatrix} 1 & 0 \\\\ 0 & 2 \\end{pmatrix}$ is:', '$$\\lambda^2 - 3\\lambda + 2 = 0$$', '$$\\lambda^2 + 3\\lambda + 2 = 0$$', '$$\\lambda^2 - 3\\lambda - 2 = 0$$', '$$\\lambda^2 + 2 = 0$$', 'A'),
('Maths', 'If $A$ and $B$ are two events such that $P(A) = 0.5$, $P(B) = 0.7$ and $P(A \\cup B) = 0.8$, then $P(A \\cap B)$ is:', '$0.4$', '$0.2$', '$0.5$', '$0.7$', 'A'),
('Maths', 'The value of $i^{2025}$ is:', '$1$', '$i$', '$-i$', '$-1$', 'B'),
('Maths', 'If $A$ is an idempotent matrix (i.e., $A^2=A$), then $(I+A)^n$ is equal to:', '$$I + nA$$', '$$I + (2^n-1)A$$', '$$I + 2^nA$$', '$$I + (n-1)A$$', 'B'),
('Maths', 'The sum of the coefficients in the binomial expansion of $(1-x)^{10}$ is:', '$0$', '$1$', '$10$', '$1024$', 'A'),
('Maths', 'The number of terms common to the two $\\text{AP}$s: $2, 5, 8, \\dots$ (up to 100 terms) and $3, 8, 13, \\dots$ (up to 100 terms) is:', '$19$', '$20$', '$33$', '$50$', 'B'),
('Maths', 'If $\\alpha$ and $\\beta$ are the roots of $x^2 - 2x + 4 = 0$, then the value of $\\alpha^3 + \\beta^3$ is:', '$8$', '$16$', '$-8$', '$0$', 'C'),
('Maths', 'The maximum value of the function $f(x) = |x-1| + |x-2| + |x-3|$ is achieved at:', '$x=1$', '$x=2$', '$x=3$', 'No maximum exists', 'C'),
('Maths', 'The number of ways of selecting $4$ letters from the word $\\text{EXAMINATION}$ is:', '$136$', '$120$', '$256$', '$165$', 'A'),
('Maths', 'The product of $n^{th}$ roots of unity is:', '$1$', '$-1$', '$(-1)^{n-1}$', '$(-1)^n$', 'C'),
('Maths', 'If $A$ and $B$ are independent events, then $P(A \\mid B)$ is equal to:', '$P(A) + P(B)$', '$P(A) \\cdot P(B)$', '$P(A)$', '$P(B)$', 'C'),
('Maths', 'If $A$ is a skew-symmetric matrix of odd order, then $|A|$ is always:', 'Positive', 'Negative', 'Zero', 'Non-zero', 'C'),
('Maths', 'The sum of the infinite geometric progression $1 + \\frac{1}{2} + \\frac{1}{4} + \\dots$ is:', '$1$', '$2$', '$3$', '$\\infty$', 'B'),
('Maths', 'The mean and variance of a binomial distribution $B(n, p)$ are $4$ and $2$ respectively. The value of $p$ is:', '$1/2$', '$1/4$', '$1/8$', '$3/4$', 'A'),
('Maths', 'If the matrix $A = \\begin{pmatrix} 2 & x \\\\ 3 & -1 \\end{pmatrix}$ is singular, then the value of $x$ is:', '$3/2$', '$-2/3$', '$-3/2$', '$2/3$', 'D'),
('Maths', 'The number of common tangents to the circles $x^2 + y^2 = 4$ and $x^2 + y^2 - 6x - 8y + 24 = 0$ is:', '$1$', '$2$', '$3$', '$4$', 'B'),
('Maths', 'The equation of the tangent to the curve $y = \\tan x$ at the point $(0, 0)$ is:', '$y = 0$', '$x = 0$', '$y = x$', '$y = -x$', 'C'),
('Maths', 'If $\\omega$ is a non-real cube root of unity, then the value of $(1 - \\omega + \\omega^2)(1 + \\omega - \\omega^2)$ is:', '$1$', '$2$', '$4$', '$8$', 'C'),
('Maths', 'The number of permutations of $n$ distinct objects taken $r$ at a time, $P(n, r)$, is given by:', '$$\\frac{n!}{r!}$$', '$$\\frac{n!}{(n-r)!}$$', '$$\\frac{n!}{r! (n-r)!}$$', '$$(n-r)!$$', 'B'),
('Maths', 'The number of solutions to $\\sin 2x = 1$ in the interval $[0, 2\\pi]$ is:', '$1$', '$2$', '$3$', '$4$', 'B'),
('Maths', 'The value of $\\sum_{r=0}^{n} C(n, r) 2^r$ is:', '$2^n$', '$3^n$', '$n \\cdot 2^n$', '$n \\cdot 3^n$', 'B'),
-- ------------------------------------------------------------------------------------------------------
-- CALCULUS (Limits, Continuity, Differentiation, Applications of Derivatives, Integration, Differential Equations) - 35 Questions
-- ------------------------------------------------------------------------------------------------------
('Maths', 'The value of the integral $\\int_{0}^{\\frac{\\pi}{2}} \\frac{\\sqrt{\\sin x}}{\\sqrt{\\sin x} + \\sqrt{\\cos x}} dx$ is:', '$0$', '$1$', '$$\\frac{\\pi}{2}$$', '$$\\frac{\\pi}{4}$$', 'D'),
('Maths', 'The limit of $\\lim_{x \\to 0} \\frac{\\sin x - x}{x^3}$ is:', '$1/6$', '$-1/6$', '$1/3$', '$-1/3$', 'B'),
('Maths', 'If $y = e^{\\sin x}$, then $\\frac{dy}{dx}$ is equal to:', '$e^{\\sin x} \\cos x$', '$\\cos x e^{\\cos x}$', '$e^{\\sin x} \\sin x$', '$e^{\\sin x}$', 'A'),
('Maths', 'The interval in which the function $f(x) = x^3 - 6x^2 + 5$ is decreasing is:', '$(-\\infty, 0)$', '$(0, 4)$', '$(4, \\infty)$', '$(-2, 2)$', 'B'),
('Maths', 'The area bounded by the curve $y = 2x - x^2$ and the line $y = x$ is:', '$$\\frac{1}{6}$$ sq. units', '$$\\frac{1}{3}$$ sq. units', '$$\\frac{1}{2}$$ sq. units', '$$\\frac{5}{6}$$ sq. units', 'A'),
('Maths', 'The degree of the differential equation $\\left(1 + \\left(\\frac{dy}{dx}\\right)^2\\right)^{\\frac{3}{2}} = \\frac{d^2y}{dx^2}$ is:', '$1$', '$2$', '$3$', 'Not defined', 'B'),
('Maths', 'The value of $\\int \\tan^{-1}x \\, dx$ is:', '$x \\tan^{-1}x + \\frac{1}{2} \\ln(1+x^2) + C$', '$x \\tan^{-1}x - \\frac{1}{2} \\ln(1+x^2) + C$', '$$x \\tan^{-1}x - \\ln(1+x^2) + C$$', '$$\\frac{1}{1+x^2} + C$$', 'B'),
('Maths', 'The maximum value of the function $f(x) = x + \\sin x$ on the interval $[0, \\pi]$ is:', '$0$', '$1$', '$$\\pi$$', '$$\\pi + 1$$', 'D'),
('Maths', 'The limit $\\lim_{n \\to \\infty} \\left(1 + \\frac{1}{n}\\right)^{2n}$ is equal to:', '$e$', '$e^2$', '$1/e$', '$1/e^2$', 'B'),
('Maths', 'If $f(x) = |x^2 - 1|$, the number of points where $f(x)$ is not differentiable is:', '$0$', '$1$', '$2$', '$3$', 'C'),
('Maths', 'The derivative of $\\sin^{-1} (2x \\sqrt{1-x^2})$ with respect to $x$ is:', '$$\\frac{2}{\\sqrt{1-x^2}}$$', '$$\\frac{1}{\\sqrt{1-x^2}}$$', '$$\\frac{2}{\\sqrt{1+x^2}}$$', '$$\\frac{1}{\\sqrt{1+x^2}}$$', 'A'),
('Maths', 'The minimum value of $f(x) = 2x^3 - 3x^2 - 12x + 5$ in the interval $[-2, 3]$ is:', '$-15$', '$12$', '$20$', '$2$', 'A'),
('Maths', 'The general solution of the differential equation $\\frac{dy}{dx} = e^{x-y}$ is:', '$e^x + e^y = C$', '$e^x - e^y = C$', '$e^x + e^{-y} = C$', '$e^x - e^{-y} = C$', 'A'),
('Maths', 'The value of the integral $\\int \\frac{\\cos 2x - \\cos 2\\alpha}{\\cos x - \\cos \\alpha} dx$ is:', '$2(\\sin x + x \\cos \\alpha) + C$', '$2(\\sin x - x \\cos \\alpha) + C$', '$$2(\\sin x + x \\sin \\alpha) + C$$', '$$2(\\cos x + x \\cos \\alpha) + C$$', 'A'),
('Maths', 'The value of $f''(2)$ for the function $f(x) = x^3 - 4x^2 + 7x - 10$ is:', '$4$', '$8$', '$-4$', '$2$', 'A'),
('Maths', 'The value of $\\int_0^{2\pi} |\\cos x| dx$ is:', '$0$', '$2$', '$4$', '$1$', 'C'),
('Maths', 'The order of the differential equation representing the family of curves $y^2 = a(b-x)$ is:', '$1$', '$2$', '$3$', '$4$', 'B'),
('Maths', 'The area of the region bounded by $y = |x|$ and $y = 1$ is:', '$1$ sq. units', '$2$ sq. units', '$1/2$ sq. units', '$3/2$ sq. units', 'A'),
('Maths', 'The value of $\\lim_{x \\to 0} \\frac{\\tan x - x}{x - \\sin x}$ is:', '$1/2$', '$2$', '$1$', '$-1/2$', 'B'),
('Maths', 'If $f(x) = \\ln (\\sec x + \\tan x)$, then $f''(\\pi/4)$ is:', '$$\\sqrt{2}$$', '$2$', '$$1/\\sqrt{2}$$', '$$1/2$$', 'A'),
('Maths', 'The radius of the circle $x^2 + y^2 + 4x - 6y + 12 = 0$ is:', '$1$', '$2$', '$3$', '$4$', 'A'),
('Maths', 'The value of the integral $\\int \\frac{1}{x^2 - a^2} dx$ is:', '$$\\frac{1}{2a} \\ln \\left|\\frac{x-a}{x+a}\\right| + C$$', '$$\\frac{1}{2a} \\ln \\left|\\frac{x+a}{x-a}\\right| + C$$', '$$\\frac{1}{a} \\tan^{-1} \\frac{x}{a} + C$$', '$$\\sin^{-1} \\frac{x}{a} + C$$', 'A'),
('Maths', 'The solution of the differential equation $\\frac{dy}{dx} = \\frac{x+y}{x}$ is:', '$y = x \\ln|x| + C x$', '$y = x \\ln|x| + C$', '$y = \\frac{1}{x} \\ln|x| + C$', '$y = x^2 \\ln|x| + C$', 'A'),
('Maths', 'The value of $\\int_{-\\pi}^{\\pi} \\sin^3 x \\cos^2 x \\, dx$ is:', '$$\\pi$$', '$1$', '$0$', '$-1$', 'C'),
('Maths', 'The slope of the normal to the curve $y = 2x^2 + 3 \\sin x$ at $x=0$ is:', '$3$', '$-3$', '$1/3$', '$-1/3$', 'D'),
('Maths', 'The critical points of $f(x) = x^{2/3} (6-x)^{1/3}$ are:', '$0$ and $4$', '$2$ and $6$', '$0$ and $6$', '$2$ and $4$', 'A'),
('Maths', 'The definite integral $\\int_{1}^{e} \\ln x \\, dx$ is equal to:', '$1$', '$e$', '$e-1$', '$1-e$', 'A'),
('Maths', 'The particular solution of $e^x \\tan y \\, dx + (1-e^x) \\sec^2 y \\, dy = 0$ with $y(0) = \\pi/4$ is:', '$(1-e^x) \\tan y = 1$', '$e^x \\tan y = 1$', '$(1-e^x) \\cot y = 1$', '$(e^x - 1) \\tan y = 1$', 'A'),
('Maths', 'The value of $\\lim_{x \\to 0} \\frac{\\sqrt{1+x} - 1}{x}$ is:', '$0$', '$1/2$', '$1$', '$2$', 'B'),
('Maths', 'If $f(x) = x^2$ and $g(x) = \\sin x$, then the value of $(g \\circ f)(x)$ is:', '$$\\sin(x^2)$$', '$$\\sin^2 x$$', '$$x^2 \\sin x$$', '$$\\sin x^2$$', 'A'),
('Maths', 'The length of the sub-tangent to the parabola $y^2 = 4ax$ at any point $(x, y)$ is:', '$y$', '$x$', '$a$', '$2x$', 'D'),
('Maths', 'The equation of the tangent to the hyperbola $\\frac{x^2}{a^2} - \\frac{y^2}{b^2} = 1$ at $(x_1, y_1)$ is:', '$$\\frac{x x_1}{a^2} + \\frac{y y_1}{b^2} = 1$$', '$$\\frac{x x_1}{a^2} - \\frac{y y_1}{b^2} = 1$$', '$$\\frac{x}{a} - \\frac{y}{b} = 1$$', '$$\\frac{x}{a} + \\frac{y}{b} = 1$$', 'B'),
('Maths', 'The value of $\\int \\frac{\\sec x}{\\sec x + \\tan x} dx$ is:', '$$\\tan x + \\sec x - x + C$$', '$$\\tan x - \\sec x + x + C$$', '$$\\sec x - \\tan x + x + C$$', '$$\\sec x + \\tan x + x + C$$', 'A'),
('Maths', 'The area under the curve $y = e^x$ from $x=0$ to $x=1$ is:', '$e$', '$e-1$', '$1-e$', '$1$', 'B'),
('Maths', 'The solution of the linear differential equation $\\frac{dy}{dx} + P y = Q$ is:', '$$y \\cdot e^{\\int P dx} = \\int Q \\cdot e^{\\int P dx} dx + C$$', '$$y \\cdot e^{-\\int P dx} = \\int Q \\cdot e^{\\int P dx} dx + C$$', '$$y \\cdot e^{\\int Q dx} = \\int P \\cdot e^{\\int Q dx} dx + C$$', '$$y = \\int (Q-P) dx$$', 'A'),
-- ------------------------------------------------------------------------------------------------------
-- COORDINATE GEOMETRY (2D & 3D, Conics, Lines, Planes) - 20 Questions
-- ------------------------------------------------------------------------------------------------------
('Maths', 'The eccentricity of the ellipse $\\frac{x^2}{25} + \\frac{y^2}{9} = 1$ is:', '$3/5$', '$4/5$', '$5/4$', '$5/3$', 'B'),
('Maths', 'The equation of the directrix of the parabola $y^2 = 8x$ is:', '$x = -2$', '$x = 2$', '$y = -2$', '$y = 2$', 'A'),
('Maths', 'The distance between the parallel planes $2x - 2y + z + 3 = 0$ and $4x - 4y + 2z + 5 = 0$ is:', '$1/6$', '$1/3$', '$1/2$', '$2/3$', 'A'),
('Maths', 'The equation of the circle passing through the origin and making intercepts $a$ and $b$ on the coordinate axes is:', '$x^2 + y^2 = a^2 + b^2$', '$x^2 + y^2 - ax - by = 0$', '$x^2 + y^2 + ax + by = 0$', '$x^2 + y^2 + 2ax + 2by = 0$', 'B'),
('Maths', 'The lines $\\frac{x-1}{2} = \\frac{y-2}{3} = \\frac{z-3}{4}$ and $\\frac{x-2}{3} = \\frac{y-3}{4} = \\frac{z-4}{5}$ are:', 'Parallel', 'Intersecting', 'Skew', 'Perpendicular', 'C'),
('Maths', 'The maximum number of normal chords that can be drawn from a point on the parabola $y^2 = 4ax$ is:', '$1$', '$2$', '$3$', '$4$', 'B'),
('Maths', 'The vertex of the parabola $x^2 + 4x + 2y - 7 = 0$ is:', '$(-2, 11/2)$', '$(-2, -11/2)$', '$(-2, 2)$', '$(-2, -2)$', 'B'),
('Maths', 'The distance of the point $(1, 2, 3)$ from the $y$-axis is:', '$$\\sqrt{10}$$', '$$\\sqrt{13}$$', '$$2$$', '$$\\sqrt{5}$$', 'A'),
('Maths', 'The angle between the asymptotes of the hyperbola $\\frac{x^2}{a^2} - \\frac{y^2}{a^2} = 1$ is:', '$$30^{\\circ}$$', '$$45^{\\circ}$$', '$$60^{\\circ}$$', '$$90^{\\circ}$$', 'D'),
('Maths', 'The point of concurrency of the altitudes of a triangle is called the:', 'Centroid', 'Incenter', 'Circumcenter', 'Orthocenter', 'D'),
('Maths', 'The equation of the plane passing through $(1, 2, 3)$ and parallel to the plane $x - 2y + 3z - 5 = 0$ is:', '$x - 2y + 3z = 6$', '$x - 2y + 3z = 4$', '$x - 2y + 3z = 1$', '$x - 2y + 3z = 0$', 'A'),
('Maths', 'The length of the latus rectum of the hyperbola $9x^2 - 16y^2 = 144$ is:', '$9/2$', '$9/4$', '$8/3$', '$3/2$', 'B'),
('Maths', 'The condition for the line $y = mx + c$ to be tangent to the parabola $y^2 = 4ax$ is:', '$c = am$', '$c = a/m$', '$c = m/a$', '$c^2 = am$', 'B'),
('Maths', 'The reflection of the point $(2, 1, 3)$ in the $xy$-plane is:', '$(-2, -1, -3)$', '$(-2, 1, 3)$', '$(2, 1, -3)$', '$(-2, -1, 3)$', 'C'),
('Maths', 'The area of the circle that passes through the foci of the ellipse $\\frac{x^2}{16} + \\frac{y^2}{9} = 1$ and has its center at $(0, 3)$ is:', '$16\\pi$', '$9\\pi$', '$25\\pi$', '$7\\pi$', 'A'),
('Maths', 'The angle between the pair of lines $ax^2 + 2hxy + by^2 = 0$ is given by $\\tan \\theta = $:', '$$\\frac{\\sqrt{h^2 - ab}}{a+b}$$', '$$\\frac{2 \\sqrt{h^2 - ab}}{a-b}$$', '$$\\frac{2 \\sqrt{h^2 - ab}}{a+b}$$', '$$\\frac{h^2 - ab}{a+b}$$', 'C'),
('Maths', 'The coordinates of the foot of the perpendicular from the origin on the plane $2x - 3y + 4z - 6 = 0$ are:', '$$\\left(\\frac{12}{29}, \\frac{-18}{29}, \\frac{24}{29}\\right)$$', '$$\\left(\\frac{12}{13}, \\frac{-18}{13}, \\frac{24}{13}\\right)$$', '$$\\left(\\frac{2}{3}, \\frac{-1}{3}, \\frac{4}{3}\\right)$$', '$$\\left(\\frac{1}{2}, \\frac{-3}{2}, 2\\right)$$', 'A'),
('Maths', 'The ratio in which the $xy$-plane divides the line segment joining the points $(-1, 3, 4)$ and $(2, -5, 6)$ is:', '$2:3$', '$3:2$', '$2:3$ externally', '$2:3$ internally', 'C'),
('Maths', 'The distance of the point $(1, 0, 0)$ from the line $\\frac{x-1}{2} = \\frac{y+1}{-3} = \\frac{z+10}{8}$ is:', '$$\\sqrt{13}$$', '$$3$$', '$$\\sqrt{5}$$', '$$\\sqrt{6}$$', 'B'),
('Maths', 'The eccentricity of a rectangular hyperbola is:', '$$\\sqrt{2}$$', '$$2$$', '$$\\sqrt{3}$$', '$$1/\\sqrt{2}$$', 'A'),
-- ------------------------------------------------------------------------------------------------------
-- VECTORS AND 3D GEOMETRY (Vectors, Scalar Triple Product, Vector Triple Product, Lines and Planes in 3D) - 15 Questions
-- ------------------------------------------------------------------------------------------------------
('Maths', 'If $\\mathbf{a}, \\mathbf{b}, \\mathbf{c}$ are coplanar vectors, then the scalar triple product $[\\mathbf{a} \\, \\mathbf{b} \\, \\mathbf{c}]$ is equal to:', '$1$', '$-1$', '$0$', '$|\\mathbf{a}| |\\mathbf{b}| |\\mathbf{c}| \\sin\\theta$', 'C'),
('Maths', 'The area of the parallelogram whose adjacent sides are $\\mathbf{a} = 3\\mathbf{i} + \\mathbf{j} + 4\\mathbf{k}$ and $\\mathbf{b} = \\mathbf{i} - \\mathbf{j} + \\mathbf{k}$ is:', '$5\\sqrt{3}$ sq. units', '$10$ sq. units', '$2\\sqrt{3}$ sq. units', '$6\\sqrt{2}$ sq. units', 'A'),
('Maths', 'The projection of the vector $\\mathbf{a} = 2\\mathbf{i} - 3\\mathbf{j} + 6\\mathbf{k}$ on the vector $\\mathbf{b} = \\mathbf{i} + 2\\mathbf{j} + 2\\mathbf{k}$ is:', '$2$', '$3$', '$4$', '$5$', 'B'),
('Maths', 'The angle between the vectors $\\mathbf{a} = \\mathbf{i} + 2\\mathbf{j} + 3\\mathbf{k}$ and $\\mathbf{b} = -\\mathbf{i} + 2\\mathbf{j} + 3\\mathbf{k}$ is:', '$$\\cos^{-1} (6/7)$$', '$$\\cos^{-1} (12/14)$$', '$$\\cos^{-1} (12/\\sqrt{14})$$', '$$\\cos^{-1} (12/14)$$', 'B'),
('Maths', 'The value of $\\mathbf{a} \\cdot (\\mathbf{a} \\times \\mathbf{b})$ is:', '$|\\mathbf{a}|^2 |\\mathbf{b}|$', '$0$', '$|\\mathbf{a}| |\\mathbf{b}| \\sin\\theta$', '$|\\mathbf{a}|^2$', 'B'),
('Maths', 'If the position vectors of $A$ and $B$ are $2\\mathbf{i} - \\mathbf{j} + 3\\mathbf{k}$ and $3\\mathbf{i} - 5\\mathbf{j} + 7\\mathbf{k}$, then the vector $\\vec{AB}$ is:', '$$5\\mathbf{i} - 6\\mathbf{j} + 10\\mathbf{k}$$', '$$-5\\mathbf{i} + 6\\mathbf{j} - 10\\mathbf{k}$$', '$$\\mathbf{i} - 4\\mathbf{j} + 4\\mathbf{k}$$', '$$- \\mathbf{i} + 4\\mathbf{j} - 4\\mathbf{k}$$', 'C'),
('Maths', 'The shortest distance between the $z$-axis and the line $\\frac{x-1}{2} = \\frac{y-2}{3} = \\frac{z-3}{4}$ is:', '$$\\sqrt{5}$$', '$$1$$', '$$2$$', '$$\\sqrt{2}$$', 'B'),
('Maths', 'The equation of the plane parallel to the vectors $\\mathbf{a}$ and $\\mathbf{b}$ and passing through a point with position vector $\\mathbf{r}_0$ is:', '$$\\mathbf{r} \\cdot (\\mathbf{a} \\times \\mathbf{b}) = \\mathbf{r}_0 \\cdot (\\mathbf{a} \\times \\mathbf{b})$$', '$$\\mathbf{r} \\cdot \\mathbf{a} = \\mathbf{r}_0 \\cdot \\mathbf{b}$$', '$$\\mathbf{r} = \\mathbf{r}_0 + \\lambda (\\mathbf{a} \\times \\mathbf{b})$$', '$$\\mathbf{r} = \\mathbf{r}_0 + \\lambda \\mathbf{a} + \\mu \\mathbf{b}$$', 'A'),
('Maths', 'The volume of the tetrahedron with vertices $(0, 0, 0)$, $(1, 0, 0)$, $(0, 1, 0)$, and $(0, 0, 1)$ is:', '$1/2$', '$1/3$', '$1/6$', '$1$', 'C'),
('Maths', 'The condition for the line $\\frac{x-x_1}{l} = \\frac{y-y_1}{m} = \\frac{z-z_1}{n}$ to lie in the plane $ax + by + cz + d = 0$ is:', '$al + bm + cn = 0$', '$ax_1 + by_1 + cz_1 + d = 0$', '$al + bm + cn = 0$ AND $ax_1 + by_1 + cz_1 + d = 0$', '$al + bm + cn \\neq 0$', 'C'),
('Maths', 'If $|\\mathbf{a} + \\mathbf{b}| = |\\mathbf{a} - \\mathbf{b}|$, then the vectors $\\mathbf{a}$ and $\\mathbf{b}$ are:', 'Parallel', 'Collinear', 'Perpendicular', 'Unit vectors', 'C'),
('Maths', 'The vector equation of a line passing through two points $\\mathbf{a}$ and $\\mathbf{b}$ is:', '$$\\mathbf{r} = \\mathbf{a} + \\lambda \\mathbf{b}$$', '$$\\mathbf{r} = \\lambda \\mathbf{a} + \\mu \\mathbf{b}$$', '$$\\mathbf{r} = (1-\\lambda) \\mathbf{a} + \\lambda \\mathbf{b}$$', '$$\\mathbf{r} = \\mathbf{a} + \\mathbf{b} + \\lambda$$', 'C'),
('Maths', 'The magnitude of the projection of $\\mathbf{a}$ on $\\mathbf{b}$ is:', '$$\\frac{|\\mathbf{a} \\times \\mathbf{b}|}{|\\mathbf{b}|}$$', '$$\\frac{\\mathbf{a} \\cdot \\mathbf{b}}{|\\mathbf{b}|}$$', '$$\\frac{\\mathbf{a} \\cdot \\mathbf{b}}{|\\mathbf{a}|}$$', '$|\\mathbf{a}| \\cos\\theta$', 'B'),
('Maths', 'The perpendicular distance of the origin from the plane $x + y + z = 3$ is:', '$1$', '$$\\sqrt{3}$$', '$3$', '$$1/\\sqrt{3}$$', 'B'),
('Maths', 'The unit vector perpendicular to both $\\mathbf{i} + \\mathbf{j}$ and $\\mathbf{j} + \\mathbf{k}$ is:', '$$\\frac{1}{\\sqrt{3}} (\\mathbf{i} - \\mathbf{j} + \\mathbf{k})$$', '$$\\frac{1}{\\sqrt{3}} (\\mathbf{i} + \\mathbf{j} - \\mathbf{k})$$', '$$\\frac{1}{\\sqrt{3}} (\\mathbf{i} - \\mathbf{j} - \\mathbf{k})$$', '$$\\frac{1}{\\sqrt{3}} (\\mathbf{i} + \\mathbf{j} + \\mathbf{k})$$', 'A'),
-- ------------------------------------------------------------------------------------------------------
-- TRIGONOMETRY AND FUNCTIONS (Inverse Trig, General Solutions, Properties of Triangles, Functions) - 15 Questions
-- ------------------------------------------------------------------------------------------------------
('Maths', 'The principal value of $\\sin^{-1} \\left(\\frac{-1}{2}\\right)$ is:', '$$\\pi/6$$', '$$- \\pi/6$$', '$$\\pi/3$$', '$$- \\pi/3$$', 'B'),
('Maths', 'The number of solutions of the equation $\\tan x + \\sec x = 2 \\cos x$ in the interval $[0, 2\\pi]$ is:', '$1$', '$2$', '$3$', '$4$', 'B'),
('Maths', 'If $f: R \\to R$ is a function defined by $f(x) = x^2$, then the function is:', 'One-one (Injective)', 'Onto (Surjective)', 'Bijective', 'Neither one-one nor onto', 'D'),
('Maths', 'The value of $\\sin^{-1} (\\sin 3)$ is:', '$3 - \\pi$', '$3$', '$$\\pi - 3$$', '$$2\\pi - 3$$', 'C'),
('Maths', 'The period of the function $f(x) = \\sin(\\frac{\\pi x}{2}) + 2 \\cos(\\frac{\\pi x}{4})$ is:', '$2$', '$4$', '$6$', '$8$', 'D'),
('Maths', 'In a $\\triangle ABC$, $\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C} = k$. This law is called:', 'Cosecant Rule', 'Cosine Rule', 'Sine Rule', 'Tangent Rule', 'C'),
('Maths', 'The domain of the function $f(x) = \\sqrt{4 - x^2}$ is:', '$$(-\\infty, 2]$$', '$$(2, \\infty)$$', '$[-2, 2]$', '$$(0, 2]$$', 'C'),
('Maths', 'The general solution of $\\cos 4x = \\cos 2x$ is:', '$x = n\\pi$', '$x = n\\pi/2$', '$x = n\\pi/3$', '$x = 2n\\pi/3$', 'C'),
('Maths', 'The range of the function $f(x) = |x-1|$ is:', '$[0, \\infty)$', '$$(-\\infty, \\infty)$$', '$[1, \\infty)$', '$$(0, \\infty)$$', 'A'),
('Maths', 'The value of $\\tan^{-1}(1) + \\tan^{-1}(2) + \\tan^{-1}(3)$ is:', '$$\\pi/2$$', '$$\\pi$$', '$$3\\pi/4$$', '$$-3\\pi/4$$', 'B'),
('Maths', 'In a $\\triangle ABC$, the value of $b \\cos C + c \\cos B$ is:', '$a$', '$b$', '$c$', '$R$', 'A'),
('Maths', 'If $f(x) = \\frac{x-1}{x+1}$ then $f(f(x))$ is equal to:', '$$x$$', '$$1/x$$', '$$-x$$', '$$-1/x$$', 'D'),
('Maths', 'The value of $\\sin 18^{\\circ}$ is:', '$$\\frac{\\sqrt{5} - 1}{4}$$', '$$\\frac{\\sqrt{5} + 1}{4}$$', '$$\\frac{1 - \\sqrt{5}}{4}$$', '$$\\frac{\\sqrt{3}}{2}$$', 'A'),
('Maths', 'The identity $\\tan^{-1} x + \\tan^{-1} y = \\tan^{-1} \\left(\\frac{x+y}{1-xy}\\right)$ holds true if:', '$xy > 1$', '$xy < 1$', '$xy = 1$', '$xy \\le 1$', 'B'),
('Maths', 'The number of functions from a set $A$ with $m$ elements to a set $B$ with $n$ elements is:', '$m^n$', '$n^m$', '$P(m, n)$', '$C(m, n)$', 'B');
